version: '3.8'

services:
  ai-lens-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for caching (uncomment to use)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: PostgreSQL for data storage (uncomment to use)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: ailens
  #     POSTGRES_USER: ailens
  #     POSTGRES_PASSWORD: changeme
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  redis_data:
  postgres_data: